### PR TITLE
Updated the Detection Mechanism by Adding False Positive Fingerprints

### PR DESCRIPTION
**Pull request by M507**
I updated the detection mechanism by adding False_Positive fingerprints. Additionally, I observed the Unbounce fingerprint on many Google 404 sites and therefore included a false positive fingerprint for that scenario.

### CODE REVIEW

**Comment by samos123** [comment]
Seeing lots of false positives for Unbound as well so this PR would be greatly appreciated. Will try out your fork @M507

**Comment by lateralusd** [comment]
Hi @M507, can you update your PR so we can merge it

**Comment by M507** [comment]
ofc, I will take a look at this soon.

**Comment by M507** [comment]
Updated https://github.com/LukaSikic/subzy/pull/35

**Pull request closed without merging**
